### PR TITLE
Add 5.4, 5.5, and main CI

### PR DESCRIPTION
**Pull request by Lukasa**
Adds Swift 5.4, 5.5, and main to CI.

### CODE REVIEW

**Comment by Lukasa** [comment]
@tomerd Hey Tom this also needs some updates to the CI:

1. Add a 5.4 job as Required
2. Add a 5.5 job as Not Required
3. Add a main job as Not Required

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
also looks like the Dockerfile needs to be updated to reflect rubygems changes, we needed to do similar thing with swift-nio and other packages

**Review by glbrntt — APPROVED** [review]
LGTM

**Pull request merged**
